### ISSUE TITLE
how set profile

### ISSUE THREAD

**Issue by Kisung** [Ketouem/flask-boto3#1]
I have multiple profiles...
How can configure additional credential named profiles?

**Comment by GedRap** [comment]
I second this. Boto3 covers a lot of services and you might want to have different sets of keys and use different regions for each of them (e.g. SQS FIFO is available in a small number of regions).

**Comment by Ketouem** [comment]
Thanks to https://github.com/Ketouem/flask-boto3/pull/3 this is now possible by setting `BOTO3_PROFILE`.
