### ISSUE TITLE
Is there a specific reason why boto3 is locked to <1.4.0?

### ISSUE THREAD

**Issue by GedRap** [Ketouem/flask-boto3#2]
Is there known breaking changes or is it simply because it hasn't been tested with newer versions?

**Comment by Ketouem** [comment]
No specific reason indeed, it has just not been tested with a more recent version. I'd be happy to have any feedback about it btw 😸

**Comment by jasco** [comment]
At least for my use-case, I have been using it with boto3 1.4.x for some time without a problem.  I just upgraded to 1.5.x.  My automated tests still pass but I haven't deployed it yet.

**Comment by Ketouem** [comment]
You're totally right @jasco, works fine with those versions. I've updated the `Pipfile` to reflect those changes.
