### ISSUE TITLE
Flask-boto3 is passing the 'profile_name' keyword argument to resource method

### ISSUE THREAD

**Issue by cheickmec** [Ketouem/flask-boto3#4]
When calling the `resources` method of my flask_boto3 instance, the latter fails when establishing a connection due to the fact that it passes the `profile_name` keyword argument to when it calls `cns.update({svc: sess.resource(svc, *args, **kwargs)})`. I have attached a screenshot of the stacktrace
<img width="1422" alt="screen shot 2017-11-19 at 5 05 34 pm" src="https://user-images.githubusercontent.com/12375818/32996120-960bfaec-cd4c-11e7-8364-e1fccd653a12.png">

**Comment by boroivanov** [comment]
@cheickmec, the issue will be fixed with https://github.com/Ketouem/flask-boto3/pull/5. My apologies for breaking this for you.

**Comment by Ketouem** [comment]
@cheickmec I've merged @boroivanov fix into master, could you re-test it so that I can release a new version on pypi ?

**Comment by cheickmec** [comment]
Thanks @boroivanov and @Ketouem. Issue fixed

**Comment by Ketouem** [comment]
Nice, I've pushed a new minor release `0.3.1` that contains this fix. 🎉
